### ISSUE TITLE
Broken link for "Source Code" button

### ISSUE THREAD

**Issue by anthonyandersonfg** [learnwithjason/learnwithjason.dev#30]
The **Source Code** button of [Build a Full-Stack Serverless App With Next.js & Fauna](https://www.learnwithjason.dev/build-a-full-stack-serverless-app-with-next-js-and-fauna) episode is broken.

![image](https://user-images.githubusercontent.com/67703565/147508998-89c88539-866d-4d33-bf6b-43efa8c47ad1.png)

I think there must be a typo in the JSON file for this episode.

**Comment by MVAodhan** [comment]
> The **Source Code** button of [Build a Full-Stack Serverless App With Next.js & Fauna](https://www.learnwithjason.dev/build-a-full-stack-serverless-app-with-next-js-and-fauna) episode is broken.
> 
> ![image](https://user-images.githubusercontent.com/67703565/147508998-89c88539-866d-4d33-bf6b-43efa8c47ad1.png)
> 
> I think there must be a typo in the JSON file for this episode.

Thanks for bringing that to our attention Anthony, that should be fixed now. My apologies
