### ISSUE TITLE
Wrong Episode Link Provided On The Page

### ISSUE THREAD

**Issue by ra-kesh** [learnwithjason/learnwithjason.dev#46]
The below episode is redirecting to the wrong episode...please have a look...thank you

[[Scheduled Functions (Cron Jobs) With Netlify](https://www.learnwithjason.dev/scheduled-functions-cron-jobs-with-netlify)]

**Comment by jlengstorf** [comment]
@ra-kesh  thanks for the heads up! We’ll get this sorted ASAP

**Comment by MVAodhan** [comment]
Thank you for bringing that to our attention @ra-kesh. That should be fixed now, sorry for the inconvenience.
