### ISSUE TITLE
Please explore these Cool things. 

### ISSUE THREAD

**Issue by ghost** [learnwithjason/learnwithjason.dev#47]
When I see a cool website like yours, I would like to know the cost of loading speed, interactivity, data apis, hosting, & databases. What I would do is just copy the url of the website & go to page speed insights (https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.learnwithjason.dev%2F)  & web dev measure (https://web.dev/measure/) & see what the results are interms of Time to Interactive, Largest Contentful Paint & First Contentful Paint.

As you can see, If you test your site that LCP, TTI, FCP is not really good. There are some of ideas that I suggest, you might see in the future. But don't consider rebuilding your website now, Just see these things, & experiment with them.

1. The Meta Framework
 Just Cool Meta Frameworks are Emerging & getting population now. If you take Solid Start, Qwik & Marko, they are really Awesome. That they are trying to solve the most important performance bottlenecks of our Applications such as :-

   A. Rendering
    I don't prefer async rendering      because it can be blocking & take seconds to first paint. So Solid Start & Marko gives you HTML Streaming (to not block rendering & sending static files) with small or no js.

   B. Bundle Sizes
    As React is Really huge, Framework build on Top of React have much huge bundle Sizes & Code to Execute, once the App hydrates, be Interactive. If you just add analytics scripts in your site you might end up with mbs of js to load & Execute. Frameworks like Solid Start, Qwik & Marko only loads like 40 kbs or no js as you like.

   C. Hydration Time
     As the framework bundle gets huge & huge, the hydration time or Time to be Interactive will get larger as we need to execute the huge bundle of code to make the app interactive & attach event handlers & more. But with Qwik & Marko you don't need to think about this & Solid Start will only take about 100 - 200 ms.

 2. API's
  As server less is going to the Edge. It's a Joy to use Cloudflare workers, Cloudflare Pages & Deno Deploy. Workers are globally distributed & sits closer to end users & workers can be used for Server Side Rendering (also called Edge Side Rendering). This gives your users a great UX as you app & your API's are awesome fast. Also Databases are going at the edge like faunadb does. Also content delivery system like cloudinary does. Also Graphql is really usefull in here to just fetch a data that we need.

Just Explore these things that I recommend to You.
  1. Cloudflare workers & Pages
  2. Solid Start, Qwik & Marko
  3. Faunadb & Cloudinary

Just see Ryan Carniato's Streams like this one https://m.youtube.com/watch?v=8hlo9uPrpr4 & Also try to make your website PWA with workbox & vite plugin pwa.

I am not saying your tech stack is bad but there are some things that you can make to make your web site awesome fast.

**Comment by jlengstorf** [comment]
hey, thanks for taking the time to write all this up

I ran the test you suggested and I'm pretty okay with the results:

<img width="1136" alt="Screen Shot 2022-02-28 at 4 45 01 PM" src="https://user-images.githubusercontent.com/163561/156083330-712ef9bf-825c-4de7-b44a-73993dee32d4.png">

I'm a fan of the tools you mentioned, and I've had [Ryan talking about SolidJS](https://www.learnwithjason.dev/lets-learn-solid-js) as well as episodes about [Cloudinary](https://www.learnwithjason.dev/better-assets-with-cloudinary-and-graphql) (which is in use on this site already) and [Fauna](https://www.learnwithjason.dev/custom-discount-codes-with-fauna-tito-and-shopify)

thanks again!

**Comment by ghost** [comment]
Did you see the mobile scores? 
Yes, using a websites in desktop is really Awesome because our desktops has good RAM, Memory, CPU cores, but when we come to mobiles these things are limited! Also if you has relatively slow network speed or if you need to bring a huge bit of data to our ui from an API, Async Rendering is going to be blocking & will take seconds to render & hydrate, so performance will get worse.

![Screenshot_20220302-025838_Brave.jpg](https://user-images.githubusercontent.com/96905008/156113692-e910817a-f150-4ec7-a0e9-3e74e4c7d623.jpg)

Note that I am writing these in my phone, I don't have a pc. I am using Github Mobile.
