### ISSUE TITLE
All (except one) embedded video on tag page is the same

### ISSUE THREAD

**Issue by raae** [learnwithjason/learnwithjason.dev#49]
<img width="1776" alt="CleanShot 2022-05-10 at 15 05 33@2x" src="https://user-images.githubusercontent.com/478531/167635390-238d4a69-a225-48f2-a9fb-be4b9835f497.png">

All, but the first one, is "Convert Markdown & CMS Content Into ..."

It is [this page](https://www.learnwithjason.dev/topic/cloudinary), but also see it happening on older videos on other tag pages.

**Comment by jlengstorf** [comment]
Oh no. I think I know what this is. YouTube has a bug with playlists where they skip to the first item in a playlist if the index is over 200. I'll look into remove the playlist query params on tagged videos 👀
