### ISSUE TITLE
link not found

### ISSUE THREAD

**Issue by Renato66** [learnwithjason/learnwithjason.dev#50]
![image](https://user-images.githubusercontent.com/9284273/179111019-407bb799-a9ef-4ae1-bb94-be8f872902bb.png)

[here](https://functions.netlify.com/example/creating-an-api-with-hasura/) we have a link to this repo, both view code and [Direct link to function](https://github.com/learnwithjason/learnwithjason.dev/blob/main/functions/schedule.js) have broken links

**Comment by jlengstorf** [comment]
hmm, that's no good — I don't control that site, but let's see if we can figure out who does 😄 

@rstavchansky is this site one you control? if so, could you help us fix this broken link? here's a permalink to fix this and make sure my code changes don't break it again:
https://github.com/learnwithjason/learnwithjason.dev/blob/f429560843388fab8c932a62df245071a4411bac/site/netlify/functions/api-schedule.ts

thank you!

**Comment by rstavchansky** [comment]
@jlengstorf It looks like we have some broken builds going on for the Functions example site. I'll alert the folks over in DXE to see if we can move this forward.
