### ISSUE TITLE
Broken link: /newsletter`

### ISSUE THREAD

**Issue by petar-i-todorov** [learnwithjason/learnwithjason.dev#55]
This link resulted in a 404: https://www.learnwithjason.dev/newsletter`

**Comment by petar-i-todorov** [comment]
The https://www.learnwithjason.dev/newsletter link actually works fine. But when you click on the "Subscribe to the newsletter" button from the home page, you get redirected to a wrong URL - https://www.learnwithjason.dev/newsletter` instead of https://www.learnwithjason.dev/newsletter . Probably a typo

**Comment by jlengstorf** [comment]
@petardotjs thanks so much for reporting this and fixing it! I saw #56, which I really appreciate. I left a comment over there on some runaway formatter issues

thank you!
