### ISSUE TITLE
Typo in Astro Typesafe Collections webpage

### ISSUE THREAD

**Issue by levic** [learnwithjason/learnwithjason.dev#66]
In step 6 of the Astro Typesafe Collections webpage there is a [`<content></content>` tag](https://github.com/learnwithjason/learnwithjason.dev/blob/91258c7f53187e2d46b01b0743b756677895dfd5/sites/blog/src/pages/blog/typesafe-markdown-astro-content-collections.mdx?plain=1#L487) (which doesn't work) whereas the repo [here](https://github.com/learnwithjason/astro-content-collections/blob/3571588/src/pages/blog/%5Bslug%5D.astro#L34) and [video](https://youtu.be/TfD4RW2gR-s?t=660) contain the correct `<Content />`.

Thanks for the collections tutorial, documentation for astro 2.0 is pretty scarce right now!

**Comment by jlengstorf** [comment]
@all-contributors add @levic for content

**Comment by jlengstorf** [comment]
thanks so much!
