### ISSUE TITLE
The video link on Let's Learn Eleventy page resolves to an Astro episode

### ISSUE THREAD

**Issue by azangru** [learnwithjason/learnwithjason.dev#81]
Steps to reproduce:
1. Visit the page for [Let's Learn Eleventy episode](https://www.learnwithjason.dev/lets-learn-eleventy)

<img width="1214" alt="image" src="https://github.com/learnwithjason/learnwithjason.dev/assets/6834224/7a9d7821-cb28-43c5-b03c-2798da856ce8">

2. Click on the video

<img width="1158" alt="image" src="https://github.com/learnwithjason/learnwithjason.dev/assets/6834224/81c82a2e-fe1e-4c25-93e4-7bef353b4fcd">

Troll level: 💯

**Comment by jlengstorf** [comment]
ah shit

okay, I know what this bug is (YouTube playlists can only have 200 things before they start to break) but I'm not sure why it's back. gotta dig in

**Comment by jlengstorf** [comment]
okay, this is fixed now — I removed the playlist details for now. if I can figure out how to make it work reliably I'll add it back later, but tbh I have no idea if anyone used that feature in the first place so not super worried about it

thanks again!
